import { mkdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { scanRepo } from "./scan.ts";
import { generateReadme } from "./readme.ts";
import { honestyPass } from "./honesty.ts";
import { renderFactsSummary, renderHonesty } from "./report.ts";
import type { Finding, RepoFacts } from "./types.ts";

export { scanRepo, generateReadme, honestyPass };
export type { Finding, RepoFacts };

export interface RunOptions {
  path: string;
  write?: boolean;
  out?: string;
  json?: boolean;
  strict?: boolean;
}

export interface RunResult {
  facts: RepoFacts;
  readme: string;
  findings: Finding[];
}

export function analyze(path: string): RunResult {
  const root = resolve(path);
  const facts = scanRepo(root);
  return { facts, readme: generateReadme(facts), findings: honestyPass(facts) };
}

/** CLI entry. Returns the process exit code. */
export function run(opts: RunOptions): number {
  const result = analyze(opts.path);
  const { facts, readme, findings } = result;

  if (opts.json) {
    process.stdout.write(JSON.stringify({ facts, readme, findings }, null, 2) + "\n");
  } else if (opts.write) {
    const outDir = opts.out ? resolve(opts.out) : join(facts.root, ".repolish");
    mkdirSync(outDir, { recursive: true });
    const readmePath = join(outDir, "README.draft.md");
    const reportPath = join(outDir, "honesty-report.md");
    writeFileSync(readmePath, readme);
    writeFileSync(reportPath, honestyMarkdown(findings, facts));
    process.stdout.write(renderFactsSummary(facts) + "\n");
    process.stdout.write(renderHonesty(findings, facts) + "\n\n");
    process.stdout.write(`Wrote:\n  ${readmePath}\n  ${reportPath}\n`);
    process.stdout.write(`\nReview the draft, then copy it over your real README when you're happy.\n`);
  } else {
    // Default: human report to stdout, README draft fenced so it's easy to read or pipe.
    process.stdout.write(renderFactsSummary(facts) + "\n");
    process.stdout.write(renderHonesty(findings, facts) + "\n");
    process.stdout.write(`\n${"─".repeat(60)}\nREADME draft (use --write to save it):\n${"─".repeat(60)}\n\n`);
    process.stdout.write(readme + "\n");
  }

  const highCount = findings.filter((f) => f.severity === "high").length;
  return opts.strict && highCount > 0 ? 1 : 0;
}

/** Markdown version of the honesty report (for --write). */
function honestyMarkdown(findings: Finding[], f: RepoFacts): string {
  const head = `# Honesty report — ${f.name}\n\n_Generated by repolish. Each item is a claim the repo can't currently back up._\n`;
  if (!f.existingReadme) return head + `\nNo existing README to audit.\n`;
  if (findings.length === 0) return head + `\n✅ No overclaims detected against what the repo can prove.\n`;
  const items = findings
    .map(
      (fd) =>
        `### \`${fd.claim}\` — ${fd.severity.toUpperCase()} (line ${fd.line})\n\n` +
        `> ${fd.snippet}\n\n` +
        `- **Why flagged:** ${fd.reason}\n` +
        `- **Honest fix:** ${fd.suggestion}\n`,
    )
    .join("\n");
  return head + `\n${items}`;
}
