import type { RepoFacts } from "./types.ts";

const TODO = "<!-- TODO -->";

/** Only badges we can actually back up get rendered. Unverifiable badges
 *  (coverage %, downloads, version) are listed as commented-out suggestions
 *  the user can enable once they're true — never auto-asserted. */
function badges(f: RepoFacts): string {
  const out: string[] = [];

  if (f.hasCI && f.repoOwner && f.repoName && f.ciFiles[0]) {
    out.push(
      `[![CI](https://github.com/${f.repoOwner}/${f.repoName}/actions/workflows/${f.ciFiles[0]}/badge.svg)](https://github.com/${f.repoOwner}/${f.repoName}/actions)`,
    );
  }
  if (f.license && f.license !== "custom") {
    const enc = encodeURIComponent(f.license);
    out.push(`![License](https://img.shields.io/badge/license-${enc}-blue.svg)`);
  }
  if (f.language) {
    out.push(`![${f.language}](https://img.shields.io/badge/built%20with-${encodeURIComponent(f.language)}-informational.svg)`);
  }

  const suggestions =
    `<!-- Optional badges — uncomment ONLY once each is true & has a source:\n` +
    `[![npm](https://img.shields.io/npm/v/${f.name}.svg)](https://www.npmjs.com/package/${f.name})\n` +
    `![coverage](https://img.shields.io/badge/coverage-__%25-brightgreen.svg)  <- needs a real coverage report\n` +
    `-->`;

  return (out.length ? out.join("\n") : `<!-- No badge could be verified from the repo yet. -->`) + `\n\n` + suggestions;
}

function tagline(f: RepoFacts): string {
  if (f.description && f.description.trim()) return `**${f.description.trim()}**`;
  return `**${TODO} one honest sentence: what ${f.name} does, and for whom.**`;
}

function quickStart(f: RepoFacts): string {
  const lines: string[] = [];
  // Clone line if we know the remote — otherwise a generic clone placeholder.
  if (f.repoUrl) lines.push(`git clone ${f.repoUrl}.git`, `cd ${f.repoName ?? f.name}`);
  if (f.installCmd) lines.push(f.installCmd);
  if (f.runCmd) lines.push(f.runCmd);
  if (lines.length === 0) {
    // Last-resort: still emit a real, runnable shape rather than the literal "TODO".
    lines.push(`git clone <your-repo-url>`, `cd ${f.name}`);
  }
  return "```bash\n" + lines.join("\n") + "\n```";
}

function comparison(f: RepoFacts): string {
  return [
    `## How it compares`,
    ``,
    `> Honesty rule: fill a cell only with something you can verify today. Delete any`,
    `> row or column you can't back up — an empty-but-true table beats a full-but-false one.`,
    ``,
    `|  | **${f.name}** | Alternative A | Alternative B |`,
    `|---|:---:|:---:|:---:|`,
    `| ${TODO} capability | ✅ | ❓ | ❓ |`,
    `| ${TODO} capability | ✅ | ❓ | ❓ |`,
    `| ${TODO} capability | ❓ | ❓ | ❓ |`,
    ``,
    `<!-- ✅ = verified · ❓ = unknown/unclaimed · ❌ = explicitly does not. Don't write ✅ on a hunch. -->`,
  ].join("\n");
}

function whatIsIt(f: RepoFacts): string {
  const body = f.description?.trim()
    ? f.description.trim()
    : `${TODO} 2–3 sentences: the problem ${f.name} solves and who it's for.`;
  return [`## What is ${f.name}?`, ``, body].join("\n");
}

function features(f: RepoFacts): string {
  const scriptNames = Object.keys(f.scripts).filter((s) => !["test", "lint", "format"].includes(s));
  const bullets =
    scriptNames.length > 0
      ? scriptNames.slice(0, 5).map((s) => `- \`${f.packageManager ?? "npm"} run ${s}\` — ${TODO} what it does`)
      : [`- ${TODO} feature one`, `- ${TODO} feature two`, `- ${TODO} feature three`];
  return [`## Features`, ``, ...bullets].join("\n");
}

function footer(f: RepoFacts): string {
  const lic = f.license && f.license !== "custom" ? f.license : `${TODO} license`;
  return [`## License`, ``, lic + (f.existingReadmePath ? "" : ` — ${TODO} add a LICENSE file.`)].join("\n");
}

/** Build the full premium-but-honest README draft. The hero name is ALWAYS the
 *  repo's real name and the quick-start is ALWAYS a real command — so a blank or
 *  placeholder repo can't yield a high-scoring draft (the M1 robustness guard). */
export function generateReadme(f: RepoFacts): string {
  const hero = [
    `<div align="center">`,
    ``,
    `# ${f.name}`,
    ``,
    tagline(f),
    ``,
    badges(f),
    ``,
    `</div>`,
  ].join("\n");

  return [
    hero,
    ``,
    whatIsIt(f),
    ``,
    `## Quick start`,
    ``,
    quickStart(f),
    ``,
    features(f),
    ``,
    comparison(f),
    ``,
    footer(f),
    ``,
    `---`,
    `<sub>Draft generated by repolish — review every <code>TODO</code> and the comparison table before shipping.</sub>`,
    ``,
  ].join("\n");
}
